### ISSUE TITLE
Launching To-do List

### ISSUE THREAD

**Issue by albertpratomo** [emillycamille/accurate-bot#90]
- [x] Launching Date: 1 april
- [x] Name: Naya! (@tanya.naya)
- [x] Apply ke FB (Carlson)
- [x] Prepare Facebook Page -> theme color Yellow (Adiet Carlson)
- [x] Design profile photo, cover photo, content posts (Adiet Carlson)
- [x] Create IG account (Adiet Carlson)
- [x] Konten IG + Fb Page (Adiet Carlson)

- [x] Announcement via Accurate Newsletter & email? -> 29/3 Darwin minta tim Accurate siapin materi (Darwin)
- [x] Test bot and report the issues here: #91 (All)

- [x] Investigate usage analytics in Fb messenger (Albert)
- [ ] Dialog flow (Albert)
- [x] Create privacy page: iubenda (Carlson)
- [x] Fix bugs #91 (Albert)
